version: '3.8'
volumes:
  elasticsearch-volume:

services:
  app:
    container_name: nestjs-app
    build: .
    entrypoint: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - redis
      - elasticsearch

  elasticsearch:
    container_name: nestjs-elasticsearch
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch-volume:/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 1024M

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: nestjs-kibana
    ports:
      - 5601:5601

  redis:
    container_name: nestjs-redis
    image: redis:6.2.5-alpine3.14
